=== e-jacquome/mean-spiele/src/server/auth/service/json/users.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Benutzerkennungen",
    "description": "Benutzerkennungen mit Passwoerter und Rollen",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "_id": {
                "description": "ID",
                "type": "string",
                "pattern": "^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$"
            },
            "username": {
                "description": "Benutzername bzw. Loginname",
                "type": "string",
                "minLength": 2
            },
            "password": {
                "type": "string",
                "minLength": 60,
                "maxLength": 60
            },
            "email": {
                "type": "string",
                "format":"email"
            },
            "roles": {
                "description": "Rollen",
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "mitarbeiter",
                        "abteilungsleiter",
                        "kunde"
                    ]
                },
                "uniqueItems": true
            }
        },
        "required": [
            "_id",
            "username",
            "password",
            "email"
        ],
        "additionalProperties": false
    },
    "uniqueItems": true
}

=== e-jacquome/mean-spiele/src/server/auth/service/json/users.json
[
    {
        "_id": "20000000-0000-0000-0000-000000000001",
        "username": "admin",
        "password": "$2b$12$jC0vLwqFtvikW9hrKL4RZ.ZMeaW5r/jYrNkm.ub23bMWL/mE2O20O",
        "email": "admin@hska.de",
        "roles": [
            "admin",
            "mitarbeiter",
            "abteilungsleiter",
            "kunde"
        ]
    },
    {
        "_id": "20000000-0000-0000-0000-000000000002",
        "username": "eric.jacquome",
        "password": "$2b$12$jC0vLwqFtvikW9hrKL4RZ.ZMeaW5r/jYrNkm.ub23bMWL/mE2O20O",
        "email": "eric.jacquome@jbgb.de",
        "roles": [
            "admin",
            "mitarbeiter",
            "abteilungsleiter",
            "kunde"
        ]
    },
    {
        "_id": "20000000-0000-0000-0000-000000000003",
        "username": "bene.bender",
        "password": "$2b$12$jC0vLwqFtvikW9hrKL4RZ.ZMeaW5r/jYrNkm.ub23bMWL/mE2O20O",
        "email": "bene.bender@jbgb.de",
        "roles": [
            "mitarbeiter"
        ]
    },
    {
        "_id": "20000000-0000-0000-0000-000000000004",
        "username": "raphael.brand",
        "password": "$2b$12$jC0vLwqFtvikW9hrKL4RZ.ZMeaW5r/jYrNkm.ub23bMWL/mE2O20O",
        "email": "raphael.brand@jbgb.de",
        "roles": [
            "kunde"
        ]
    },
    {
        "_id": "20000000-0000-0000-0000-000000000005",
        "username": "hjördis.goettsche",
        "password": "$2b$12$jC0vLwqFtvikW9hrKL4RZ.ZMeaW5r/jYrNkm.ub23bMWL/mE2O20O",
        "email": "hjördis.goettsche@jbgb.de",
        "roles": [
            "kunde"
        ]
    },
    {
        "_id": "20000000-0000-0000-0000-000000000006",
        "username": "karl.kunde",
        "password": "$2b$12$jC0vLwqFtvikW9hrKL4RZ.ZMeaW5r/jYrNkm.ub23bMWL/mE2O20O",
        "email": "karls.kunde@jbgb.de",
        "roles": [
            "kunde"
        ]
    },
    {
        "_id": "20000000-0000-0000-0000-000000000007",
        "username": "nils.nichtkunde",
        "password": "$2b$12$jC0vLwqFtvikW9hrKL4RZ.ZMeaW5r/jYrNkm.ub23bMWL/mE2O20O",
        "email": "nils.nichtkunde@jbgb.de"
    }
]
